- name: Create Registry Directory
  file:
    path: "{{ podman_registry_path }}"
    state: directory

- name: Deploy the Registry
  podman_container:
    name: "{{ podman_registry_name }}"
    image: registry:2
    privileged: yes
    state: started
    volume: "{{ podman_registry_path }}:{{ podman_registry_path }}"
    restart_policy: always
    detach: yes
    ports:
      - 5000:5000

- name: Define the New Registry
  replace:
    path: "{{ registry_config_path }}"
    regexp: '\[registries.insecure\]\nregistries = \[\]'
    replace: "[registries.insecure]\nregistries = ['localhost:5000']"

- name: Restart Podman
  service:
    name: podman
    state: restarted
