- name: Create Registry Directory
  file:
    path: "{{ registry['path'] }}"
    state: directory

- name: Deploy the Registry
  containers.podman.podman_container:
    name: "{{ registry['name'] }}"
    image: registry:2
    privileged: yes
    state: started
    volume: "{{ registry['path'] }}:{{ registry['path'] }}"
    restart_policy: always
    detach: yes
    ports:
      - "{{ registry['port'] }}:{{ registry['port'] }}"

- name: Define the New Registry
  replace:
    path: "{{ registry['config_path'] }}"
    regexp: '\[registries.insecure\]\nregistries = \[\]'
    replace: "[registries.insecure]\nregistries = ['{{ registry['address'] }}']"
  notify:
   - Restart Podman

- name: Force Handlers
  meta: flush_handlers
