---

- hosts: all
  become: true
  roles:
    - rm_container  # stop service container
    - rm_image      # remove service image
    - rm_registry   # shut down and remove local registry
    - rm_podman     # uninstall podman