---

- hosts: all
  become: true
  vars_files:
    - vars/setup_vars.yml
    - vars/uninstall_options.yml
  roles:
    - rm_container  # stop service container
    - rm_image      # remove service image
    - rm_registry   # shut down and remove local registry
    - rm_podman     # uninstall podman