---

- hosts: all
  become: true
  vars:
    - /vars/setup_vars.yml
  roles:
    - podman      # install podman
    - registry    # launch local registry
    - image       # create service image and push it to the local registry
    - container   # create container service from image