- name: Uninstall Podman
  dnf:
    name: podman
    state: absent
  when: options['remove_podman'] | bool

- name: Remove residual directories
  file:
    name: "{{ item }}"
    state: absent
  with_items:
   - /etc/containers
   - /var/lib/containers/
   - /etc/subuid
   - /etc/subgid
   when: options['remove_podman_residuals'] | bool