- name: Uninstall Podman
  dnf:
    name: podman
    state: absent

- name: Remove residual directories
  file:
    name: "{{ item }}"
    state: absent
    recurse: yes
    with_items:
     - /etc/containers
     - /var/lib/containers/
     - /etc/subuid
     - /etc/subgid