- name: Launch Container with Service
  containers.podman.podman_container:
    name: "{{ service['name'] }}"
    image: "{{ registry['address'] }}:{{ registry['port'] }}/{{ service['name'] }}"
    state: started
    ports:
      - "{{ service['port'] }}:80"