- name: Launch Container with Service
  podman_container:
    name: "{{ service['name'] }}"
    image: "{{ registry['address'] }}/{{ service['name'] }}"
    state: started
    ports:
      - "{{ service['port'] }}:80"