- name: Create Temporary Directory
  file:
    path: /tmp/buildfiles
    state: directory

- name: Copy Build Files to Remote Host
  copy:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "/tmp/buildfiles/{{ item }}"
  with_items:
    - Dockerfile
    - index.html


- name: Build Image from Dockerfile
  containers.podman.podman_image:
    name: "{{ registry['address'] }}:{{ registry['port'] }}/{{ service['name'] }}"
    pull: no
    path: "/tmp/buildfiles/"

- name: Push Image to Local Registry
  containers.podman.podman_image:
    name: "{{ registry['address'] }}:{{ registry['port'] }}/{{ service['name'] }}"
    pull: no
    push: yes

- name: Remove Temporary Directory
  file:
    path: /tmp/buildfiles
    state: absent

- name: Remove Intermediate Image
  containers.podman.podman_image:
    name: httpd
    state: absent
