- name: Shut Down Registry
  containers.podman.podman_container:
    name: "{{ registry['name'] }}"
    state: absent

- name: Remove Registry from Config File
  replace:
    path: "{{ registry['config_path'] }}"
    regexp: "{{ regex['front'] + registry['address'] + regex['back'] }}"
    replace: "[registries.insecure]\nregistries = []"
  notify:
   - Restart Podman

- name: Remove Local Directory
  file:
    path: "{{ registry['path']  }}"
    state: absent