- name: Shut Down Registry
  podman_container:
    name: "{{ registry['name'] }}"
    state: absent

- name: Remove Registry from Config File
  replace:
    path: "{{ registry['config_path'] }}"
    regexp: "\[registries.insecure\]\nregistries = \['{{ registry['address'] }}'\]"
    replace: "[registries.insecure]\nregistries = []"

- name: Restart Podman
  service:
    name: podman
    state: restarted

- name: Remove Local Directory
  file:
    path: "{{ registry['path']  }}"
    state: absent